# Generated by Django 5.2.3 on 2025-06-28 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('sensors', '0002_alter_iotsensorset_options_iotdevice_devicegroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='croppredictionrequest',
            name='farmer',
            field=models.ForeignKey(blank=True, help_text='Farmer who requested the prediction (for manual inputs)', limit_choices_to={'role': 'farmer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='croppredictionrequest',
            name='manual_input',
            field=models.ForeignKey(blank=True, help_text='Link to manual crop input if this prediction is from manual data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_requests', to='dashboard.manualcropinput'),
        ),
        migrations.AlterField(
            model_name='croppredictionrequest',
            name='community_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'community_admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='croppredictionrequest',
            name='sensor_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_predictions', to='sensors.iotsensorset'),
        ),
    ]
