# Generated by Django 5.2.3 on 2025-06-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location_address',
            field=models.TextField(blank=True, help_text='Full address for location reference', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate for precise location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate for precise location', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Global Administrator'), ('community_admin', 'Community Administrator'), ('technician', 'Field Technician'), ('farmer', 'Farmer')], default='farmer', max_length=20),
        ),
    ]
