# Generated by Django 5.2.3 on 2025-06-28 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📄', max_length=50)),
                ('color_class', models.CharField(default='green', help_text='CSS color class (e.g., green, blue, purple, orange)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Grant Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.CharField(help_text='e.g., ₹6,000/year, Up to ₹50,000', max_length=100)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('eligibility', models.TextField(help_text='Who can apply for this grant')),
                ('required_documents', models.TextField(blank=True)),
                ('application_url', models.URLField(blank=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_always_open', models.BooleanField(default=False, help_text='No specific deadline')),
                ('duration', models.CharField(blank=True, help_text='e.g., 3 years, One-time', max_length=100)),
                ('interest_rate', models.CharField(blank=True, help_text='For loans', max_length=50)),
                ('coverage', models.CharField(blank=True, help_text='Coverage area or beneficiaries', max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='grants.grantcategory')),
            ],
            options={
                'ordering': ['-is_featured', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('documents_submitted', models.BooleanField(default=False)),
                ('verification_complete', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='grants.grant')),
            ],
            options={
                'ordering': ['-application_date'],
                'unique_together': {('grant', 'applicant')},
            },
        ),
    ]
